name: Test GitHub Output Bug

on:
  workflow_dispatch:

jobs:
  test-github-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/create-pull-request
