name: Test GitHub Output Bug

on:
  workflow_dispatch:

jobs:
  test-github-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set ENTRY_ID to GitHub Output
        id: set-entry-id
        run: |
          # Generate a test ENTRY_ID
          ENTRY_ID="6802418398468691450"
          echo "Generated ENTRY_ID: $ENTRY_ID"
          
          # Set to GITHUB_OUTPUT
          echo "ENTRY_ID=$ENTRY_ID" >> $GITHUB_OUTPUT
          echo "Successfully set ENTRY_ID to GITHUB_OUTPUT"

      - name: prepare step
        id: prepare
        env:
          ENTRY_ID: ${{ steps.set-entry-id.outputs.ENTRY_ID }}
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "ENTRY_ID=$ENTRY_ID" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
      - name: Reference ENTRY_ID using composite action
        uses: ./.github/actions/reference-entry
        with:
          entry-id: ${{ steps.set-entry-id.outputs.ENTRY_ID }}
          branch: draft-entry-${{ steps.set-entry-id.outputs.ENTRY_ID }}
          joined-branch: ${{ format('draft-entry-{0}', steps.set-entry-id.outputs.ENTRY_ID) }}
          body: ${{ steps.prepare.outputs.BODY }}

      - name: create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          title: draft-entry-${{ steps.set-entry-id.outputs.ENTRY_ID }}
          branch: draft-entry-${{ steps.set-entry-id.outputs.ENTRY_ID }}
          body: ${{ steps.prepare.outputs.BODY }}
          delete-branch: true
          draft: false
