name: Test GitHub Output Bug

on:
  workflow_dispatch:

jobs:
  test-github-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set ENTRY_ID to GitHub Output
        id: set-entry-id
        run: |
          # Generate a test ENTRY_ID
          ENTRY_ID="test-entry-$(date +%s)"
          echo "Generated ENTRY_ID: $ENTRY_ID"
          
          # Set to GITHUB_OUTPUT
          echo "ENTRY_ID=$ENTRY_ID" >> $GITHUB_OUTPUT
          echo "Successfully set ENTRY_ID to GITHUB_OUTPUT"
      
      - name: Reference ENTRY_ID and create COMBINED_ENTRY_ID
        id: reference-entry-id
        env:
          ENTRY_ID: ${{ steps.set-entry-id.outputs.ENTRY_ID }}
          COMBINED_ENTRY_ID: prefix-${{ steps.set-entry-id.outputs.ENTRY_ID }}
          JOINED_ENTRY_ID: ${{ join('prefix-', steps.set-entry-id.outputs.ENTRY_ID) }}
        run: |
          echo "ENTRY_ID: $ENTRY_ID"
          echo "COMBINED_ENTRY_ID: $COMBINED_ENTRY_ID"
          echo "JOINED_ENTRY_ID: $JOINED_ENTRY_ID"
